name: .NET Core

on: [push]

env:
  DOTNET_SDK_VERSION: '5.0.103'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
    - name: Build with dotnet
      run: dotnet build
    - name: Test with dotnet
      run: dotnet test

  publish_managed:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
    - name: Publish Windows x86 Release
      run: dotnet publish TypedocConverter -c Release -o WindowsBuildx86 -r win-x86 --no-self-contained /p:PublishSingleFile=true
    - name: Publish Windows x64 Release
      run: dotnet publish TypedocConverter -c Release -o WindowsBuildx64 -r win-x64 --no-self-contained /p:PublishSingleFile=true
    - name: Publish Windows ARM Release
      run: dotnet publish TypedocConverter -c Release -o WindowsBuildARM -r win-arm --no-self-contained /p:PublishSingleFile=true
    - name: Publish Windows ARM64 Release
      run: dotnet publish TypedocConverter -c Release -o WindowsBuildARM64 -r win-arm64 --no-self-contained /p:PublishSingleFile=true
    - name: Publish Linux x64 Release
      run: dotnet publish TypedocConverter -c Release -o LinuxBuildx64 -r linux-x64 --no-self-contained /p:PublishSingleFile=true
    - name: Publish Linux ARM Release
      run: dotnet publish TypedocConverter -c Release -o LinuxBuildARM -r linux-arm --no-self-contained /p:PublishSingleFile=true
    - name: Publish Linux ARM64 Release
      run: dotnet publish TypedocConverter -c Release -o LinuxBuildARM64 -r linux-arm64 --no-self-contained /p:PublishSingleFile=true
    - name: Publish macOS x64 Release
      run: dotnet publish TypedocConverter -c Release -o macOSBuildx64 -r osx-x64 --no-self-contained /p:PublishSingleFile=true
    - name: Upload Windows x86 artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Windows_x86
        path: WindowsBuildx86
    - name: Upload Windows x64 artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Windows_x64
        path: WindowsBuildx64
    - name: Upload Windows ARM artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Windows_ARM
        path: WindowsBuildARM
    - name: Upload Windows ARM64 artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Windows_ARM64
        path: WindowsBuildARM64
    - name: Upload Linux x64 artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Linux_x64
        path: LinuxBuildx64
    - name: Upload Linux ARM artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Linux_ARM
        path: LinuxBuildARM
    - name: Upload Linux ARM64 artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Linux_ARM64
        path: LinuxBuildARM64
    - name: Upload macOS x64 artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: macOS_x64
        path: macOSBuildx64

  publish-native-linux:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
    - name: Publish Native Linux x64 Release
      run: dotnet publish -c Release -r linux-x64 -o LinuxNativeBuildx64 /p:NativeBuild=true
    - name: Upload Linux x64 native artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Linux_x64_Native
        path: LinuxNativeBuildx64
        
  publish-native-windows:
    runs-on: windows-2019
    needs: build_and_test

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
    - name: Publish Native Windows x64 Release
      run: dotnet publish -c Release -r win-x64 -o WindowsNativeBuildx64 /p:NativeBuild=true
    - name: Upload Windows x64 native artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Windows_x64_Native
        path: WindowsNativeBuildx64
